### ISSUE TITLE
Handicap : intégration de valeurs profils.json

### ISSUE THREAD

**Issue by Agathe-SW** [gip-inclusion/data-inclusion-schema#2]
"value": "personnes-handicapees",
    "label": "Personnes handicapées",
    "description": null
    
        "value": "personnes-en-situation-de-handicap",
    "label": "Personnes en situation de handicap",
    "description": null

**Comment by vmttn** [comment]
cc @cedricr

**Comment by cedricr** [comment]
@vmttn tu me préviens quand je peux le reporter sur DORA ?

**Comment by Agathe-SW** [comment]
![hacker](https://github.com/gip-inclusion/data-inclusion-schema/assets/56914299/38f3a20b-4891-43cc-9dbf-764306d44032)

**Comment by cedricr** [comment]
Et c’est ainsi qu’ils découvrirent que Github supporte les GIF animés… :rofl:

**Comment by vmttn** [comment]
#3
